server:
  port: 7077
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: postgres
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
